/*
 * Matrix Client-Server Client Config API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.matrix.client;

import org.hamcrest.Matchers;
import org.junit.Assert;
import org.matrix.client.ApiException;
import org.matrix.client.api.SessionManagementApi;
import org.matrix.client.model.Error;
import org.matrix.client.model.LoginRequest;
import org.matrix.client.model.LoginResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SessionManagementApi
 */
public class SessionManagementApiTest extends ApiTestBase {
    /**
     * Authenticates the user.
     *
     * Authenticates the user, and issues an access token they can use to authorize themself in subsequent requests.  If the client does not supply a &#x60;&#x60;device_id&#x60;&#x60;, the server must auto-generate one.  The returned access token must be associated with the &#x60;&#x60;device_id&#x60;&#x60; supplied by the client or generated by the server. The server may invalidate any access token previously associated with that device. See &#x60;Relationship between access tokens and devices&#x60;_.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loginTest() throws ApiException {
        Assert.assertThat(authClient.getAuthentications().size(), Matchers.greaterThan(0));
        Assert.assertThat(authClient.getAuthentication("accessToken"), Matchers.notNullValue());
    }
    
    /**
     * Invalidates a user access token
     *
     * Invalidates an existing access token, so that it can no longer be used for authorization.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logoutTest() throws ApiException {
        Assert.assertThat(authClient.getAuthentication("accessToken"), Matchers.notNullValue());
    }
    
}
